apiVersion: v1
kind: Config
clusters:
- name: bc-express-app-cluster.us-west-2.eksctl.io
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXpNREl4TlRjd09Wb1hEVE16TURVeU56SXhOVGN3T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3FRCi90aDAyWnI2MzZqWWVnMFZuaXZ6WnlyYlJIeHcrM1dRamYrTlU5RUtCcU9FTFhtT2NibExqOTZqVWdFZzZIQTkKeVFXR0VyR1I2RW1zRkkrVWd2V1RoSzRIZHp3ZXpVSW1tUnh1Y1NQcUUzcTNOOXVmemdIeTNTUDNESk1acnVkaQo1Sm1nUVJacVBBTGh6QzhlTnpMakx3VFhuZ25LWDMyaFBCaEVnYXBqSWVqcDkzZ2dpV3V3T0E2YitiaXlKbGIvCno1TzV2MzRONERKYW5oR0l3WG1KY2ZvSVkweTA2TUxMNVpoa3k4d05jK0xmc3hGeE5ucFFFeWdxekZyUjk2YU4KOXc5TVkvQ1ZUekF2d2E0WDZIMVhwdXVMV3hkT0orZi9GdVdEU1RDZmg3WUpKRFU0WmpUeThtZnNrUktpd3VGRgowckxDQXhkc2dkSEY1SExDMzAwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCYlhjdi91YitJOXcwNU8vcSt2Ujd5L1Ftc2ZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQWpNQUpCZEpFUFc3UXNrayt1KwpXa1RjRGt2cFh4M2x0b2RvODlJRFh4eHdUTVJZeXNYSzFHMWVjRGNuckJQNm96NjVtWUtFZzB0N3E5Wjk2SGJ6CmxCdjBSTzNPK0ppbnhFY3V2dFRTakRHa2k4TnRDVE8rUU9vdkV3N0xCQlRyU2lJbkx2K2ZnYTVSeGlsSkRoT0EKQ09JZUJvcDJGc3FUSkVvSkhpclM3Tk9rN01JQkZuRUgyNHIvS09NakRtL1JSeExEcy93bDBHMlIwYWNXZDFyTQpQUlI0anI4a1dVK0d5MEwrTFk1NTlWNDBmeEVKcDh5dTlacDJ2NXV2YnJCa08rL3E2ekdkeitHYlRWS2ZyUVdzClRLTVlwUUpNMHZqZjZrR2V5cWFGWWdIQ1ZBMEEwc0w2SVhFdFpib0IvOWFtK3RuODU2Y0FmdGkxWG92anhBanoKeFhBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://03FB85F8095168F145F418994744398A.gr7.us-west-2.eks.amazonaws.com
contexts:
- name: express-app-user@bc-express-app-cluster.us-west-2.eksctl.io
  context:
    cluster: bc-express-app-cluster.us-west-2.eksctl.io
    user: express-app-user@bc-express-app-cluster.us-west-2.eksctl.io
current-context: express-app-user@bc-express-app-cluster.us-west-2.eksctl.io
preferences: {}
users:
- name: express-app-user@bc-express-app-cluster.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
      - token
      - -i
      - bc-express-app-cluster
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      provideClusterInfo: false
